import Head from 'next/head'
import { Inter } from 'next/font/google'
import Products from '@/components/Products'
// import Product from './../components/Product';
import Link from 'next/link';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex justify-center align-center flex-column home'>
        <h2>WELCOME TO NEXT PROJECT</h2>
        <Link href="/products">
          <button>Go To Product Screen <img src="/images/arrow.jpg" /></button>
        </Link>
      </div>
    </>
  )
}


